---

- name: Check sonarqube tarball already downloaded
  stat:
    path: /opt/sonarqube-8.6.1.40680.zip
  register: sonar_zipfile

- name: Download sonarqube tarball
  get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-8.6.1.40680.zip
    dest: /opt
    mode: 0644
  when: sonar_zipfile.stat.exists == False

- name: Uncompress sonarqube to /opt
  unarchive:
    src: /opt/sonarqube-8.6.1.40680.zip
    dest: /opt
    remote_src: yes

- name: Check sonarqube directory exists
  stat:
    path: /opt/sonarqube
  register: sonar_dir

- name: Rename sonarqube-8.6.1
  command: ln -sf /opt/sonarqube-8.6.1.40680 /opt/sonarqube
  when: sonar_dir.stat.exists == False

- name: Create sonar group
  group:
    name: sonar
    state: present

- name: Create sonar user in sonar group
  user:
    name: sonar
    state: present
    group: sonar
    home: /opt/sonarqube

- name: Set sonarqube directory onwership
  file:
    path: /opt/sonarqube*
    state: directory
    recurse: yes
    owner: sonar
    group: sonar

- name: Config port in sonar config file.
  replace:
    path: /opt/sonarqube/conf/sonar.properties
    regexp: '#sonar.web.port=9000'
    replace: 'sonar.web.port=9000'

- name: Config port in sonar config file.
  replace:
    path: /opt/sonarqube/conf/sonar.properties
    regexp: '#sonar.host=0.0.0.0'
    replace: 'sonar.host=0.0.0.0'

- name: Config sonar user to run sonar service.
  replace:
    path: /opt/sonarqube/bin/linux-x86-64/sonar.sh
    regexp: '#RUN_AS_USER='
    replace: 'RUN_AS_USER=sonar'

- name: sonarqube systemd service file.
  blockinfile:
    path: /etc/systemd/system/sonar.service
    create: yes
    block: |
      [Unit]
      Description=SonarQube service
      After=syslog.target network.target

      [Service]
      Type=forking

      ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
      ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop

      User=sonar
      Group=sonar
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Open sonarqube service on firewall
  firewalld:
    state: enabled
    port: 9000/tcp
    permanent: yes

- name: "Enable sonarqube service on boot"
  systemd:
    name: sonar
    state: started
    enabled: yes