---
- hosts: all
  become: true
  roles:
    - base

- hosts: docker
  become: true
  roles:
    - docker

- hosts: jenkins
  become: true
  roles:
    - jenkins
    - sonarqube

- hosts: artifactory
  become: true
  roles:
    - artifactory
