---
- hosts: appserver
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker-ce
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Log into private registry and force re-authorization
      docker_login:
        registry_url: http://192.168.100.12:8000/v1
        username: jenkins
        password: jenkins
        #reauthorize: yes
    - name: Start the container
      docker_container:
        name: spring-boot-app
        image: "192.168.100.12:8000/spring-boot-sample-app:{{ DOCKER_TAG }}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080