---

- name: Download jenkins.repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import jenkins key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    state: present

- name: Install jenkins and ansible
  package:
    name:
      - jenkins
      - ansible
    state: present

- name: Start Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Sleep for 5 seconds and continue with play
  wait_for: timeout=5
  delegate_to: localhost

- name: Check jenkins is running for the first time
  stat:
    path: '/var/lib/jenkins/secrets/initialAdminPassword'
  register: init_status

- name: init password jenkin
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  when: init_status.stat.exists == True
  changed_when: false
  register: result

- name: print init password jenkins
  debug:
    var: result.stdout
  when: init_status.stat.exists == True